# LPC Configuration
# Please read the https://luckperms.net/wiki/Prefixes,-Suffixes-&-Meta before you set up.
#
# Placeholders:
# {message} - the chat message
# {name} - the player's name
# {displayname} - the player's display name / nickname
# {world} - the world name of the player's current world
# {prefix} - the player's highest priority prefix
# {suffix} - the player's highest priority suffix
# {prefixes} - the player's prefixes sorted by the highest priority
# {suffixes} - the player's suffixes sorted by the highest priority
# {username-color} - the player's or the group's username color
# {message-color} - the player's or the group's message color
#
# To reload the configuration, run '/lpc reload' command. Make sure you have the 'lpc.reload' permission assigned.
# More information can be found at https://www.spigotmc.org/resources/68965.
SuggestCommand: true
PerformCommand: false
Command: '/msg %player_name% hi!'

chat-format: "&f{prefix}{name} &8» &f{message}"
Title: '&6&lSTATISTICS &8| &7(%player_name%)'

HoverText: |-
  &7
  &8| &fMoney: &6%vault_eco_balance_formatted% ⛁
  &8| &fPlayTime: &a%statistic_time_played%
  &7
  &8▪ &fTotal Jumps: &e%statistic_jump%
  &8▪ &fTotal Deaths: &4%statistic_deaths%
  &8▪ &fTotal Kills: &c%statistic_player_kills%
# Set the format per group.
# Note: Option for more advanced users. Remove comments to run.
group-formats: